language: ruby

sudo: false

env:
  - JRUBY_OPTS="--dev -Xcext.enabled=false -Xcompile.invokedynamic=false -J-Xmx1g"

services:
  - redis
addons:
    code_climate:
        repo_token: 9fe4bb72d7e5d1dfe426d0a9e094f46ef71c33032be6111bcd1432c7bc774148
addons:
  code_climate:
    repo_token: adf08323...
addons:
  postgresql: 9.3
  artifacts:
    paths:
    - log/

cache:
  directories:
    - vendor/bundle

sudo: false

rvm:
  - jruby-1.7.16
  - jruby-head
  - jruby-9.0.0.0
  - "2.0"
  - "2.1"

jdk: oraclejdk7

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
    - rvm: jruby-9.0.0.0

before_install:
  - if [ $TRAVIS_RUBY_VERSION = 'jruby-9.0.0.0' ]; then rvm get head; rvm use --install jruby-9.0.0.0; ruby --version; fi
  - gem install bundler -v 1.9.0

install:
  # JRuby fails to resolve dependencies on newer bundler
  - bundle _1.9.0_ install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

before_script:
  - redis-cli config set save ""
  - 'RAILS_ENV=test bundle exec rake db:create db:migrate --trace'

script:
  - ./build.sh
